carsenk/denarius

denarius-qt.pro
src/alert.cpp
src/bitcoinrpc.cpp
src/db.cpp
src/init.cpp
src/irc.cpp
src/kernel.cpp
src/main.cpp
src/main.h
src/miner.cpp
src/net.cpp
src/net.h
src/qt/walletmodel.cpp
src/rpcblockchain.cpp
src/rpcnet.cpp
src/rpcsmessage.cpp
src/rpcwallet.cpp
src/smessage.cpp
src/txdb-leveldb.cpp
src/util.cpp
src/util.h
src/wallet.cpp
src/walletdb.cpp

miniupnpc api_version>=14 requires ttl arg for upnpDiscover()

revert literals and fix miniupnpc>1.9

---

src/qt/addressbookpage.cpp
src/qt/addressbookpage.h
src/qt/qrcodedialog.cpp

adds double click on receiving address tab to show qr code
sanitized qr code window (removed the address which was spilling over width)

QRCode fixes

---

src/base58.cpp
src/base58.h

Moved a bunch from base58 header to source to lower compilation time.

More reformatting of base58. Loweres compile time.

---

src/allocators.h
src/base58.cpp
src/base58.h
src/hash.cpp
src/hash.h
src/init.cpp
src/key.cpp
src/key.h
src/makefile.bsd
src/makefile.linux-mingw
src/makefile.mingw
src/makefile.osx
src/makefile.unix
src/script.cpp
src/walletdb.cpp

But yeah. Seems to work a bit better than it did :)

Masternodes PRE-ALPHA 0.000001. Still needs to go trough extended testing!

---

src/main.cpp

Fix Testnet Launchdate.

---

src/clientversion.h
src/darksend.cpp
src/kernel.cpp
src/main.cpp
src/main.h
src/miner.cpp
src/rpcrawtransaction.cpp
src/script.cpp
src/script.h

Version 2.1.0.0. Should be a big step towards working MN's. Changed mainly ConnectInputs and VerifyScript Functions to accept valid masternodes.

Masternodes correctly appending to MN List

---

src/init.cpp

Fixed Importing Masternode Error Printing

---

src/main.cpp
src/main.h
src/rpcwallet.cpp
src/smessage.cpp

New IsStandardTX Format

---

src/clientversion.h
src/json/json_spirit_writer_template.h
src/kernel.cpp
src/kernel.h
src/main.cpp
src/main.h
src/miner.cpp
src/wallet.cpp

Block 499 Issue Fixed, New POS starting on testnet on block 20k

Block 499 Issue Fixed, New POS starting on testnet on block 20k

---

src/kernel.cpp

Fixed debug string printing compile errors

Fixed debug string printing compile errors

---

src/bitcoinrpc.cpp

The fix came from zetacoin, added preprocessors for backward compatibility.
Formatting is kind of ugly, feel free to give advice or feedback on formatting.. or anything else really.

Support boost >= 1.66.0

---

src/qt/overviewpage.cpp

Should fix your segfault that occurs when a user spends a long time reading the TOU dialog and should continue to run the darksend timer once the user moves past that dialog.
Note that the rest of the code surrounded by the conditional was re-indented automatically.

apply check at darkSendStatus to fix qt TOU segfault

---

src/kernelrecord.cpp
src/qt/mintingtablemodel.cpp
src/rpcwallet.cpp
src/wallet.cpp

segfault in listaddressgroupings
fixed nonsense transactions in the staking tab

more ui fixes

---

src/main.cpp
src/main.h
src/masternode.cpp
src/masternode.h
src/net.h
src/qt/forms/masternodemanager.ui
src/qt/masternodemanager.cpp
src/wallet.cpp

New Fair Masternode Payment System
(Denarius FMPS)

v3.1 Updates - FMPS

---

src/fortunastake.cpp
src/main.cpp

reorganized blocks are already added to the chain, so we have already checked them.
save time & money and keep your head in sync, let's just let them through.

allow payments in reorged blocks

---

denarius-qt.pro
src/clientversion.h
src/fortunastake.cpp
src/fortunastake.h
src/main.cpp
src/net.cpp
src/qt/bitcoingui.cpp
src/qt/fortunastakemanager.cpp

Fix all the problems

---

src/fortunastake.cpp
src/fortunastake.h
src/main.cpp
src/net.cpp
src/net.h
src/qt/walletmodel.cpp
src/wallet.cpp

adds commands to lookup fortunastakes by vin when they aren't in the fortunastake list
this should avoid situations where a client refuses a block due to not receiving the mn yet

Fortunastake fixes

---

denariusqtubuntu.sh

openssl compile fix

---

snapcraft.yaml

This should allow the Snapcraft.io build process to proceed.

Removed datadir setup

---

hooks/bin/configure
hooks/bin/install
snapcraft.yaml
src/activefortunastake.cpp
src/init.cpp
src/util.cpp

convert to snap services
rename snap apps: daemon is now accessible via 'denarius.daemon' and qt is 'denarius'

make snap great again

---

src/util.cpp

ipv4 and ipv6 for extra addnode goodness

Add additional addnode

---

denarius-qt.pro
snapcraft.yaml
src/clientversion.h
src/init.cpp
src/makefile.unix
src/namecoin.h
src/test/ringsig_tests.cpp
src/txdb-leveldb.cpp
src/wallet.cpp

Removal of Thin Mode
Performance Updates
Addition of Name Database and key-value pairs with Egeria DNS Server (Default Port 3333)
Tons of bug fixes and improvements
OpenSSL v1.1 and v1.0.1 compatibility
Tons of new RPC commands
Tons of new flags
New Jupiter features, commands, and flags

v3.3.9.8 Latest

---

src/rpcjupiter.cpp
src/rpcwallet.cpp

Minor Updates in preparation for dPi

Minor Updates

---

src/rpcjupiter.cpp

Remote and Local Jupiter and Jupiter RPC Command IPFS Updates for Denarius

Jupiter Local/Remote IPFS Updates

---

src/util.cpp

remove old electrumx IP's and add current, remove pos.watch ipv4 and ipv6

update addnodes denarius.conf autogen

---

src/qt/trafficgraphwidget.cpp

To compile with newer QT. https://github.com/bitcoin/bitcoin/pull/19097

qt: Add missing QPainterPath include

---

denarius-qt.pro
src/base58.cpp
src/bignum.h
src/db.h
src/ddns.cpp
src/ddns.h
src/denariusrpc.cpp
src/denariusrpc.h
src/hooks.h
src/init.cpp
src/key.cpp
src/key.h
src/main.cpp
src/namecoin.cpp
src/namecoin.h
src/net.cpp
src/qt/trafficgraphwidget.cpp
src/ringsig.cpp
src/rpcblockchain.cpp
src/rpcjupiter.cpp
src/rpcwallet.cpp
src/script.cpp
src/script.h
src/smessage.cpp
src/util.cpp

More updates for NVS
Start of OpenSSL 1.1 compat (might be phased out entirely for something alternative)
Fixes to DDNS

Updates for NVS
